# Generated by Django 5.0.1 on 2024-07-08 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_couponusage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CouponUsage",
        ),
    ]
