# Generated by Django 5.0.1 on 2024-01-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourselBanner',
        ),
    ]
