# Generated by Django 5.0.1 on 2024-02-08 15:44

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_3d',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='product.jpg', upload_to=store.models.user_directory_path),
        ),
    ]
